start_listening:
  name: "Start IR Code Listening"
  description: "Start listening for the next IR code from your remote control"
  fields:
    device:
      name: "Device Name"
      description: "Name of the device (e.g., TV, AC, Soundbar)"
      required: true
      example: "tv"
      selector:
        text:
    action:
      name: "Action Name"  
      description: "Name of the action/button (e.g., power, volume_up, channel_1)"
      required: true
      example: "power"
      selector:
        text:

get_recent_codes:
  name: "Get Recent IR Codes"
  description: "Retrieve recently captured IR codes from the database"
  fields:
    device:
      name: "Device Name"
      description: "Filter by device name (optional)"
      required: false
      example: "tv"
      selector:
        text:
    limit:
      name: "Limit"
      description: "Maximum number of codes to retrieve"
      required: false
      default: 10
      example: 10
      selector:
        number:
          min: 1
          max: 100