get_recent_codes:
  name: Get Recent Codes
  description: Retrieve recently captured IR codes from database
  fields:
    device:
      name: Device
      description: Filter by device name (optional)
      required: false
      selector:
        text: {}
    action:
      name: Action
      description: Filter by action name (optional)
      required: false
      selector:
        text: {}
    limit:
      name: Limit
      description: Maximum number of codes to retrieve (default 10)
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 100

save_ir_code:
  name: Save IR Code
  description: Save an IR code to the database
  fields:
    device:
      name: Device
      description: Name of the device
      required: true
      selector:
        text: {}
    action:
      name: Action
      description: Name of the action
      required: true
      selector:
        text: {}
    event_data:
      name: Event Data
      description: IR event data (JSON string or object)
      required: true
      selector:
        text: {}

delete_ir_code:
  name: Delete IR Code
  description: Delete an IR code from the database
  fields:
    id:
      name: ID
      description: ID of the IR code to delete
      required: true
      selector:
        number:
          min: 1
